/**
 * Generates contract ABIs from Foundry artifacts. The ABIs are checked in (so the SDK builds and
 * typechecks from a fresh clone) but are never edited by hand — run `pnpm codegen` after changing
 * any Solidity, and the `abi-drift` test in CI will fail if they are stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const artifacts = resolve(here, '../../contracts/out')
const abiDir = resolve(here, '../src/abis')

const targets = [
  { contract: 'VestingWallet', symbol: 'vestingWalletAbi', file: 'vestingWallet.ts' },
  { contract: 'VaultKitFactory', symbol: 'vaultKitFactoryAbi', file: 'vaultKitFactory.ts' },
  { contract: 'VaultKitRegistry', symbol: 'vaultKitRegistryAbi', file: 'vaultKitRegistry.ts' },
] as const

const header = [
  '// AUTO-GENERATED by packages/sdk/scripts/codegen.ts — do not edit by hand.',
  '// Source: packages/contracts/out/*.json (Foundry artifacts).',
  '',
].join('\n')

mkdirSync(abiDir, { recursive: true })

for (const target of targets) {
  const artifactPath = resolve(artifacts, `${target.contract}.sol`, `${target.contract}.json`)
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as { abi: readonly unknown[] }
  const contents = `${header}export const ${target.symbol} = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
  writeFileSync(resolve(abiDir, target.file), contents)
  process.stdout.write(`generated ${target.file} (${artifact.abi.length} ABI entries)\n`)
}

const barrel = [
  header.trimEnd(),
  '',
  "export { vestingWalletAbi } from './vestingWallet.js'",
  "export { vaultKitFactoryAbi } from './vaultKitFactory.js'",
  "export { vaultKitRegistryAbi } from './vaultKitRegistry.js'",
  '',
].join('\n')

writeFileSync(resolve(abiDir, 'index.ts'), barrel)
process.stdout.write('generated index.ts\n')
